# Generated by Django 4.0.2 on 2022-04-26 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='brand',
            fields=[
                ('brand_id', models.IntegerField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('brand_name', models.CharField(max_length=100)),
                ('brand_desc', models.CharField(max_length=100)),
                ('brand_image', models.ImageField(upload_to='pics')),
            ],
        ),
        migrations.CreateModel(
            name='cart',
            fields=[
                ('cart_id', models.IntegerField(db_index=True, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='cat1',
            fields=[
                ('cat_id', models.IntegerField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('car_name', models.CharField(max_length=100)),
                ('img1', models.ImageField(upload_to='pics')),
                ('img2', models.ImageField(upload_to='pics')),
                ('img3', models.ImageField(upload_to='pics')),
            ],
        ),
        migrations.CreateModel(
            name='cat2',
            fields=[
                ('cat2_id', models.IntegerField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('car2_name', models.CharField(max_length=100)),
                ('img1', models.ImageField(upload_to='pics')),
                ('img2', models.ImageField(upload_to='pics')),
                ('img3', models.ImageField(upload_to='pics')),
            ],
        ),
        migrations.CreateModel(
            name='cat3',
            fields=[
                ('cat3_id', models.IntegerField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('car3_name', models.CharField(max_length=100)),
                ('img1', models.ImageField(upload_to='pics')),
                ('img2', models.ImageField(upload_to='pics')),
                ('img3', models.ImageField(upload_to='pics')),
            ],
        ),
        migrations.CreateModel(
            name='cat4',
            fields=[
                ('cat4_id', models.IntegerField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('car4_name', models.CharField(max_length=100)),
                ('img1', models.ImageField(upload_to='pics')),
                ('img2', models.ImageField(upload_to='pics')),
                ('img3', models.ImageField(upload_to='pics')),
            ],
        ),
        migrations.CreateModel(
            name='cat5',
            fields=[
                ('cat5_id', models.IntegerField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('car5_name', models.CharField(max_length=100)),
                ('img1', models.ImageField(upload_to='pics')),
                ('img2', models.ImageField(upload_to='pics')),
                ('img3', models.ImageField(upload_to='pics')),
            ],
        ),
        migrations.CreateModel(
            name='cat6',
            fields=[
                ('cat6_id', models.IntegerField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('car6_name', models.CharField(max_length=100)),
                ('img1', models.ImageField(upload_to='pics')),
                ('img2', models.ImageField(upload_to='pics')),
                ('img3', models.ImageField(upload_to='pics')),
            ],
        ),
        migrations.CreateModel(
            name='category',
            fields=[
                ('cat_id', models.IntegerField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('cat_name', models.CharField(max_length=100)),
                ('cat_desc', models.CharField(max_length=100)),
                ('cat_image', models.ImageField(upload_to='pics')),
            ],
        ),
        migrations.CreateModel(
            name='color',
            fields=[
                ('color_id', models.IntegerField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('color_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='customer',
            fields=[
                ('cust_id', models.IntegerField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('cust_name', models.CharField(max_length=100)),
                ('cust_email', models.CharField(max_length=100)),
                ('cust_pass', models.CharField(max_length=100)),
                ('cust_contact', models.CharField(max_length=100)),
                ('cust_address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('order_id', models.IntegerField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('order_quantity', models.IntegerField()),
                ('order_price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('product_id', models.IntegerField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('product_name', models.CharField(max_length=100)),
                ('product_brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.brand')),
                ('product_cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.category')),
            ],
        ),
        migrations.CreateModel(
            name='wishlist',
            fields=[
                ('wishlist_id', models.IntegerField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('wishlist_cust', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.customer')),
            ],
        ),
        migrations.CreateModel(
            name='wishlist_item',
            fields=[
                ('wishlist_item_id', models.IntegerField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('createdon', models.DateField()),
                ('modifiedon', models.DateField()),
                ('product_wishlist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.product')),
                ('wishlist_id_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.wishlist')),
            ],
        ),
        migrations.CreateModel(
            name='trends',
            fields=[
                ('trend_id', models.IntegerField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('prod_cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.category')),
                ('prod_trend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.product')),
            ],
        ),
        migrations.CreateModel(
            name='sales',
            fields=[
                ('sales_id', models.IntegerField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('sales_payment_mode', models.CharField(max_length=100)),
                ('sales_order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.order')),
            ],
        ),
        migrations.CreateModel(
            name='product_image',
            fields=[
                ('image_id', models.IntegerField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('img1', models.ImageField(upload_to='pics')),
                ('img2', models.ImageField(upload_to='pics')),
                ('img3', models.ImageField(upload_to='pics')),
                ('img4', models.ImageField(upload_to='pics')),
                ('prod_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.product')),
            ],
        ),
        migrations.CreateModel(
            name='product_desc',
            fields=[
                ('prod_desc_id', models.IntegerField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('prod_price', models.FloatField()),
                ('prod_quanitity', models.IntegerField()),
                ('prod_date', models.DateField()),
                ('main_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.product')),
                ('prod_color_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.color')),
                ('prodduct_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.product_image')),
            ],
        ),
        migrations.CreateModel(
            name='order_details',
            fields=[
                ('order_id', models.IntegerField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('order_quantity', models.IntegerField()),
                ('order_price', models.FloatField()),
                ('order_prod_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.order')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='order_prod_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.product'),
        ),
        migrations.CreateModel(
            name='latest',
            fields=[
                ('latest_id', models.IntegerField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('prod_time', models.TimeField()),
                ('prod_cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.category')),
                ('product_latest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.product')),
            ],
        ),
        migrations.AddField(
            model_name='color',
            name='prod_color_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.product'),
        ),
        migrations.CreateModel(
            name='cart_item',
            fields=[
                ('cart_item_id', models.IntegerField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('created_on', models.DateField()),
                ('modified_on', models.DateField()),
                ('cart_id_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.cart')),
                ('product_cart_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.product')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='cart_cust',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.customer'),
        ),
    ]
