# Generated by Django 4.0.2 on 2022-04-29 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cust_review',
            fields=[
                ('review_id', models.AutoField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('review_desc', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('feedback_id', models.AutoField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('desc', models.CharField(max_length=1000)),
            ],
        ),
        migrations.RenameField(
            model_name='cart_item',
            old_name='cart_id_fk',
            new_name='cart_fk',
        ),
        migrations.RenameField(
            model_name='cart_item',
            old_name='product_cart_id',
            new_name='product_cart',
        ),
        migrations.RenameField(
            model_name='color',
            old_name='prod_color_id',
            new_name='prod_color',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='order_prod_id',
            new_name='order_prod',
        ),
        migrations.RenameField(
            model_name='order_details',
            old_name='order_prod_id',
            new_name='order_prod',
        ),
        migrations.RenameField(
            model_name='product_desc',
            old_name='prod_color_id',
            new_name='prod_color',
        ),
        migrations.RenameField(
            model_name='product_desc',
            old_name='prodduct_image',
            new_name='product_images',
        ),
        migrations.RenameField(
            model_name='sales',
            old_name='sales_order_id',
            new_name='sales_order',
        ),
        migrations.RenameField(
            model_name='wishlist_item',
            old_name='wishlist_id_fk',
            new_name='wishlist_fk',
        ),
        migrations.AddField(
            model_name='customer',
            name='cust_chest',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='cust_neck',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='cust_shoulder',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='cust_size',
            field=models.CharField(default='XL', max_length=300),
        ),
        migrations.AddField(
            model_name='customer',
            name='cust_waist',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='order_details',
            name='cust_order',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main_app.customer'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_offer',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='brand',
            name='brand_desc',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='brand',
            name='brand_id',
            field=models.AutoField(db_index=True, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='cart_id',
            field=models.AutoField(db_index=True, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='cart_item',
            name='cart_item_id',
            field=models.AutoField(db_index=True, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='cat1',
            name='cat_id',
            field=models.AutoField(db_index=True, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='cat2',
            name='cat2_id',
            field=models.AutoField(db_index=True, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='cat3',
            name='cat3_id',
            field=models.AutoField(db_index=True, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='cat4',
            name='cat4_id',
            field=models.AutoField(db_index=True, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='cat5',
            name='cat5_id',
            field=models.AutoField(db_index=True, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='cat6',
            name='cat6_id',
            field=models.AutoField(db_index=True, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='cat_desc',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='category',
            name='cat_id',
            field=models.AutoField(db_index=True, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='color',
            name='color_id',
            field=models.AutoField(db_index=True, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cust_email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cust_id',
            field=models.AutoField(db_index=True, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.AutoField(db_index=True, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='order_details',
            name='order_id',
            field=models.AutoField(db_index=True, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.AutoField(db_index=True, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='product_desc',
            name='prod_desc_id',
            field=models.AutoField(db_index=True, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='product_image',
            name='image_id',
            field=models.AutoField(db_index=True, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='sales_id',
            field=models.AutoField(db_index=True, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='trends',
            name='trend_id',
            field=models.AutoField(db_index=True, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='wishlist_id',
            field=models.AutoField(db_index=True, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='wishlist_item',
            name='wishlist_item_id',
            field=models.AutoField(db_index=True, primary_key=True, serialize=False, unique=True),
        ),
        migrations.DeleteModel(
            name='latest',
        ),
        migrations.AddField(
            model_name='feedback',
            name='cust_feed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.customer'),
        ),
        migrations.AddField(
            model_name='cust_review',
            name='cust_review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.customer'),
        ),
        migrations.AddField(
            model_name='cust_review',
            name='prod_review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.product'),
        ),
    ]
